### PR TITLE
Fixes compatibility issues with PHPUnit 7.x

### PR DESCRIPTION
**Pull request by rdeeb**
This simple change is to make the tests run with PHPUnit7.x

### CODE REVIEW

**Comment by ericmann** [comment]
I like it, but as this will break back-compat with older versions (by forcing the most recent PHPUnit), we'll need to merge this with a version bump. Approving for now, but will merge later this week once I have a chance to update docs.

**Comment by Rayrn** [comment]
Bump. :)

**Comment by ericmann** [comment]
@brokentone I have this on my to-do list to close out by the end of the month. Hang tight :-)

**Comment by ericmann** [comment]
Replaced by #129.

**Pull request closed without merging**
